---
title: "week7_visulization"
author: "Anil Bashetty"
date: "April 14, 2019"
output: html_document
---
```{r, message=FALSE}
library(ggplot2)
library(tidyverse)
```

# Data Visualization
```{r}
### We will use the inbuilt diamonds dataset 
### Use ggplot inbuilt function with bar chart to see distribution of a categorical variable.
### Below chart shows total number of diamonds grouped by cut
ggplot(data = diamonds) +
  geom_bar(mapping = aes(x = cut))
```
```{r}
#Use ggplot inbuilt function with histogram to see distribution of a continuos variable
ggplot(data = diamonds) +
  geom_histogram(mapping = aes(x = carat), binwidth = 0.5)
```
```{r}
#Use scatterplot to see relationship between carat and price of diamonds
plot(diamonds$carat, diamonds$price)

```

```{r}
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = y), binwidth = 0.5) + ggtitle("weird diamonds$y plot")
###  The y axis is taking a lot of space even if we do not see any points on the screen. There might be some outliers which are not clearly visible here.
```

```{r}
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = y), binwidth = 0.5) +
  coord_cartesian(ylim = c(0, 60))
### This allows to see outliers

```

```{r}
### There are two ways to remove unususal values. One is to drop them and the other option, the better one is to use mutate function.
diamonds2 <- diamonds %>%   mutate(y = ifelse(y < 3 | y > 20, NA, y))

ggplot(data = diamonds2, mapping = aes(x = x, y = y)) + 
  geom_point()+ ggtitle("Diamonds$x vs Diamonds$y")

```

```{r}
### geom_point() will always show if values have been removed. na.rm function can be used to suppres that.
ggplot(data = diamonds2, mapping = aes(x = x, y = y)) + 
  geom_point(na.rm = TRUE)
```

```{r}
### Explore how the price of a diamond varies with its quality. We will need to explore the distribution of a continuous variable broken down by a categorical variable.
ggplot(data = diamonds, mapping = aes(x = price)) + 
  geom_freqpoly(mapping = aes(colour = cut), binwidth = 600)
```

```{r}
### It's difficult to see the difference in distribution because the overall counts differ so much:
ggplot(diamonds) + 
  geom_bar(mapping = aes(x = cut))
```


```{r}
### Lets flip on the y-axis to show density.
### it appears that fair diamonds (the lowest quality) have the highest average price!
ggplot(data = diamonds, mapping = aes(x = price, y = ..density..)) + 
  geom_freqpoly(mapping = aes(colour = cut), binwidth = 500)
```


```{r}
### Let's take a look at the distribution of price by cut using geom_boxplot():
### It looks like better quality diamonds are cheaper on average. 
ggplot(data = diamonds, mapping = aes(x = cut, y = price)) +
  geom_boxplot()

```

```{r}
### To visualise the covariation between categorical variables, you'll need to count the number of observations for each combination. geom_count() exists for just that.
### The size of each circle in the plot displays how many observations occurred at each combination of values.
ggplot(data = diamonds) +
  geom_count(mapping = aes(x = cut, y = color))
```